import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins,Kavoon } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar";
import Footer from './_Components/Footer';
import Providers from "@/Providers/ReactQuery.Provider";
export const inter = Inter({
  subsets:['latin']
});
export const kavoon = Kavoon({
  weight:'400',
  subsets:['latin']
})
export const poppins = Poppins({
  weight:'500',
  subsets:['latin']
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "Code Camp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <Navbar/>
        <div className="my-36 container">
           {children}
        </div>
        <Footer/>
        </Providers>
      </body>
    </html>
  );
}
